import os
import subprocess

PROJECT_DIRECTORY = os.path.realpath(os.path.curdir)

def remove_file(filepath):
    os.remove(os.path.join(PROJECT_DIRECTORY, filepath))

if __name__ == '__main__':
    # 1. Iniciar Git
    print("--- Inicializando repositorio Git ---")
    subprocess.call(['git', 'init'])
    subprocess.call(['git', 'add', '.'])
    subprocess.call(['git', 'commit', '-m', 'Initial commit generated by Cookiecutter'])

    # 2. (Opcional) Crear entorno virtual automáticamente
    # print("--- Creando venv ---")
    # subprocess.call(['python3', '-m', 'venv', '.venv'])

    print(f"¡Proyecto creado exitosamente en {PROJECT_DIRECTORY}!")